import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/nav";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      </Head>
      <body className={`overflow-x-hidden ${inter.className}`}>
        <Nav></Nav>
        {children}</body>
    </html>
  );
}
